### ISSUE TITLE
Tracking issue for SDL port

### ISSUE THREAD

**Issue by cmlsharp** [cs50/spl#26]
Todo:

- [ ] `GArc` (Easy)
- [ ] `GInteractor` (Hard)
- [ ] `GImage` (Easy)
- [ ] `GRoundRect` (Very Easy)
- [ ] `G3DRect` (Unsure, I have some questions about this)
- [ ] Key, action and timer events (Medium)
- [ ] `GTimer` (Easy)
- [ ] `GSound` (Easy)
- [ ] `install` target in Makefile (Easy)
- [ ] Decide what format the library should take (LLVM bytecode, JS, etc.)
- [ ] Graceful error handling on SDL failure (Easy)
- [ ] Removing buggy/misleading features (creation of "bst of doubles", exceptions) (Medium, depending on how much of the code relies on these features)
- [ ] Decide on which fonts to support
